### ISSUE TITLE
Should not be checked in ambient contexts

### ISSUE THREAD

**Issue by forivall** [alhugone/tslint-strict-null-checks#6]
for the [`trash`](https://npm.im/trash) module, I wrote the following definition

```
declare module 'trash' {
  namespace trash {
    type Trash = (iterable: Iterable<string> | string, opts?: {glob?: boolean}) => Promise<void>
  }
  const trash: trash.Trash
  export = trash
}
```

and then i get the error

```
tools/cli/types.d.ts
ERROR: 6:9  no-uninitialized  Variable 'trash' is uninitialized. 'undefined' is not assignable to its type.
```

**Comment by UselessPickles** [comment]
I just ran into this yesterday too. The fix is simple. The implementations of the Lint.RuleWalker used by this rule simply need to override `visitModuleDeclaration` to do nothing and return (without calling the `super.visitModuleDeclaration`). This prevents anything within a module declaration (ambient context) from even being considered by this rule.

I'll create a pull request tonight if I have time. I already tested the fix locally on my project.

**Comment by UselessPickles** [comment]
@alhugone Please review the pull request I created to fix this issue.

**Comment by UselessPickles** [comment]
@forivall In case you're not aware, you can disable this rule in specific files (your .d.ts files) by adding this comment to the top of the file:
```ts
// tslint:disable:no-uninitialized
```
This works around the bug while still allowing you to use this rule on the rest of your project. That's what I'm doing for now until the author of this project responds.

**Comment by forivall** [comment]
Yup, i've been doing that workaround too.

**Comment by alhugone** [comment]
fixed
